[package]
name = "gidth"
version = "0.1.0"
edition = "2021"

[lib]
name = "gidth"
path = "src/lib.rs"

[workspace]
members = [".", "gidth_macros"]

[dependencies]
inherent = "1.0.12"

[dependencies.gidth_macros]
path = "./gidth_macros"
